# --- Stage 1: build ---
FROM node:20 AS builder
WORKDIR /app

# Build args passed from docker compose
ARG REACT_APP_API_BASE=/api
ARG PUBLIC_URL=/
ENV REACT_APP_API_BASE=${REACT_APP_API_BASE}
ENV PUBLIC_URL=${PUBLIC_URL}

RUN npm cache clean --force
COPY package*.json ./
RUN npm install && npm install -g react-scripts

COPY . .

# This will now see REACT_APP_API_BASE and PUBLIC_URL
RUN npm run build
