# --- Stage 1: build ---
FROM node:20 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG REACT_APP_API_BASE
ENV REACT_APP_API_BASE=${REACT_APP_API_BASE}

RUN npm run build

# --- Stage 2: serve ---
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY public/avatars /usr/share/nginx/html/avatars
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
