# Generated by Django 5.0.1 on 2025-11-29 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario_text",
                    models.TextField(
                        help_text="Patient background and scenario description",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "additional_instructions",
                    models.TextField(
                        help_text="Medical history, symptoms, and additional context"
                    ),
                ),
                (
                    "enable",
                    models.BooleanField(
                        default=True, help_text="Whether this scenario is active"
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        default="Adult",
                        help_text="Patient role (Adult, Child, Elderly, etc.)",
                    ),
                ),
                (
                    "communication_preferences",
                    models.TextField(
                        blank=True,
                        help_text="How the patient prefers to communicate",
                        null=True,
                    ),
                ),
                (
                    "openid",
                    models.TextField(help_text="OpenAI Assistant ID for this scenario"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assistant Scenario",
                "verbose_name_plural": "Assistant Scenarios",
                "db_table": "assistant_scenarios",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["enable"], name="assistant_s_enable_c6287b_idx"
                    ),
                    models.Index(
                        fields=["openid"], name="assistant_s_openid_7ac73a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.TextField(help_text="Tag name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="scenarios.assistantscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "assistant_tags",
                "ordering": ["tag"],
                "unique_together": {("tag", "scenario")},
            },
        ),
    ]
