# Generated by Django 4.2 on 2026-01-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantscenario',
            name='voice',
            field=models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='nova', help_text='OpenAI TTS voice for this character', max_length=20),
        ),
    ]
