# Generated by Django 4.2 on 2026-01-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GMCCommunicationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code, e.g., 'GMC-C1'", max_length=20, unique=True)),
                ('title', models.CharField(help_text='Short title of the outcome', max_length=255)),
                ('description', models.TextField(help_text='Full description of the communication outcome')),
                ('domain', models.CharField(help_text="Domain category, e.g., 'Communication', 'Partnership'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GMC Communication Outcome',
                'verbose_name_plural': 'GMC Communication Outcomes',
                'db_table': 'gmc_communication_outcomes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MLACapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code, e.g., 'MLA-CAP-1'", max_length=20, unique=True)),
                ('title', models.CharField(help_text='Short title of the capability', max_length=255)),
                ('description', models.TextField(help_text='Full description of the capability')),
                ('category', models.CharField(help_text="Category, e.g., 'Professional Values', 'Clinical Skills'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLA Capability',
                'verbose_name_plural': 'MLA Capabilities',
                'db_table': 'mla_capabilities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MLACondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the condition', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Name of the condition/presentation', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Category of condition', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLA Condition',
                'verbose_name_plural': 'MLA Conditions',
                'db_table': 'mla_conditions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_text', models.CharField(help_text='The criterion statement to be evaluated', max_length=500)),
                ('marking_instructions', models.TextField(help_text='Detailed instructions for evaluating this criterion')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Relative weight of this criterion (1.00 = standard)', max_digits=3)),
                ('is_required', models.BooleanField(default=False, help_text='If true, must be addressed to pass overall assessment')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order within the section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
                'db_table': 'rubric_criteria',
                'ordering': ['section', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='RubricFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the framework', max_length=255)),
                ('code', models.CharField(help_text="Unique code identifier, e.g., 'SPIKES'", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the framework and its purpose')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this framework is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubric Framework',
                'verbose_name_plural': 'Rubric Frameworks',
                'db_table': 'rubric_frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RubricPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the pack', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this pack covers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pack is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubric Pack',
                'verbose_name_plural': 'Rubric Packs',
                'db_table': 'rubric_packs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RubricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_label', models.CharField(help_text='User-friendly display name', max_length=255)),
                ('internal_code', models.CharField(help_text="Internal reference code, e.g., 'RUB-SPIKES-MIG-01'", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this template covers')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('track_type', models.CharField(choices=[('generic_comms', 'Generic Communication'), ('clinical_content', 'Clinical Content')], default='clinical_content', help_text='Track classification for this template', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this template was published', null=True)),
                ('framework', models.ForeignKey(help_text='Framework this template is based on', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='rubrics.rubricframework')),
            ],
            options={
                'verbose_name': 'Rubric Template',
                'verbose_name_plural': 'Rubric Templates',
                'db_table': 'rubric_templates',
                'ordering': ['framework', 'display_label'],
            },
        ),
        migrations.CreateModel(
            name='RubricSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the section', max_length=255)),
                ('code', models.CharField(help_text="Short code, e.g., 'S', 'P', 'I', 'K', 'E', 'S2'", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this section covers')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order within the framework')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(help_text='Parent framework this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rubrics.rubricframework')),
            ],
            options={
                'verbose_name': 'Rubric Section',
                'verbose_name_plural': 'Rubric Sections',
                'db_table': 'rubric_sections',
                'ordering': ['framework', 'ordering', 'name'],
                'unique_together': {('framework', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RubricCriterionMLAMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mla_mappings', to='rubrics.rubriccriterion')),
                ('mla_capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_mappings', to='rubrics.mlacapability')),
            ],
            options={
                'verbose_name': 'Criterion MLA Mapping',
                'verbose_name_plural': 'Criterion MLA Mappings',
                'db_table': 'rubric_criterion_mla_mappings',
                'unique_together': {('criterion', 'mla_capability')},
            },
        ),
        migrations.CreateModel(
            name='RubricCriterionGMCMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmc_mappings', to='rubrics.rubriccriterion')),
                ('gmc_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_mappings', to='rubrics.gmccommunicationoutcome')),
            ],
            options={
                'verbose_name': 'Criterion GMC Mapping',
                'verbose_name_plural': 'Criterion GMC Mappings',
                'db_table': 'rubric_criterion_gmc_mappings',
                'unique_together': {('criterion', 'gmc_outcome')},
            },
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='gmc_outcomes',
            field=models.ManyToManyField(blank=True, help_text='GMC outcomes this criterion maps to', related_name='criteria', through='rubrics.RubricCriterionGMCMapping', to='rubrics.gmccommunicationoutcome'),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='mla_capabilities',
            field=models.ManyToManyField(blank=True, help_text='MLA capabilities this criterion maps to', related_name='criteria', through='rubrics.RubricCriterionMLAMapping', to='rubrics.mlacapability'),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='section',
            field=models.ForeignKey(help_text='Parent section this criterion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.rubricsection'),
        ),
        migrations.CreateModel(
            name='RubricTemplateCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order within the template')),
                ('weight_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override the criterion weight for this template', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(help_text='Criterion included in this template', on_delete=django.db.models.deletion.PROTECT, related_name='in_templates', to='rubrics.rubriccriterion')),
                ('template', models.ForeignKey(help_text='Parent template', on_delete=django.db.models.deletion.CASCADE, related_name='template_criteria', to='rubrics.rubrictemplate')),
            ],
            options={
                'verbose_name': 'Template Criterion',
                'verbose_name_plural': 'Template Criteria',
                'db_table': 'rubric_template_criteria',
                'ordering': ['template', 'ordering'],
                'unique_together': {('template', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='RubricPackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order within the pack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(help_text='Parent pack', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rubrics.rubricpack')),
                ('template', models.ForeignKey(help_text='Template included in this pack', on_delete=django.db.models.deletion.PROTECT, related_name='in_packs', to='rubrics.rubrictemplate')),
            ],
            options={
                'verbose_name': 'Pack Entry',
                'verbose_name_plural': 'Pack Entries',
                'db_table': 'rubric_pack_entries',
                'ordering': ['pack', 'ordering'],
                'unique_together': {('pack', 'template')},
            },
        ),
    ]
