"""Update Assistant table 2

Revision ID: 00e6817a7bcb
Revises: 764ef6442692
Create Date: 2025-04-21 19:20:32.565696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e6817a7bcb'
down_revision = '764ef6442692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.drop_column('past_medications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_medications', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
