"""add past_medications column

Revision ID: 764ef6442692
Revises: cc72293e6469
Create Date: 2025-04-09 07:52:42.810672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764ef6442692'
down_revision = 'cc72293e6469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_medications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.drop_column('past_medications')

    # ### end Alembic commands ###
