"""Activities

Revision ID: ad8c3984089f
Revises: 80027d05426e
Create Date: 2025-05-22 09:09:35.749532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8c3984089f'
down_revision = '80027d05426e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pre_brief', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['assistant_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_categories',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_categories')
    op.drop_table('activities')
    # ### end Alembic commands ###
