"""Update Assistant table

Revision ID: cc72293e6469
Revises: 721848ccea7a
Create Date: 2025-03-23 14:34:06.032122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc72293e6469'
down_revision = '721848ccea7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communication_preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_scenarios', schema=None) as batch_op:
        batch_op.drop_column('communication_preferences')

    # ### end Alembic commands ###
