# Generated by Django 4.2 on 2026-01-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openai_integration', '0002_increase_model_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title for the feedback', max_length=255)),
                ('content', models.TextField(help_text='Detailed feedback content')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('not-fit-to-merge', 'Not Fit to Merge'), ('fit-to-merge', 'Fit to Merge')], default='submitted', help_text='Current status of the feedback', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by admin/reviewer', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the feedback was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='Related conversation', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='openai_integration.conversation')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', '-created_at'], name='feedback_user_id_88c7db_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['conversation'], name='feedback_convers_ac90db_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', '-created_at'], name='feedback_status_711338_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['reviewed_by'], name='feedback_reviewe_a52dea_idx'),
        ),
    ]
