# Generated by Django 5.0.1 on 2025-11-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pre_brief",
                    models.TextField(
                        help_text="Pre-briefing information for the student"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Assessment categories for this activity",
                        related_name="activities",
                        to="assessments.category",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The patient scenario for this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="scenarios.assistantscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
