# Generated by Django 5.0.1 on 2026-01-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        ("assessments", "0001_initial"),
        ("rubrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="exclude_generic_comms",
            field=models.BooleanField(
                default=False,
                help_text="If true, exclude generic communication templates from evaluation",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="rubric_pack",
            field=models.ForeignKey(
                blank=True,
                help_text="Rubric pack for evaluating this activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="rubrics.rubricpack",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="DEPRECATED: Use rubric_pack instead. Assessment categories for this activity",
                related_name="activities",
                to="assessments.category",
            ),
        ),
    ]
