# Generated by Django 4.2 on 2026-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, help_text='Model used to generate this message', max_length=100),
        ),
    ]
