# Generated by Django 4.2 on 2026-01-12 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openai_integration', '0002_increase_model_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('results', models.JSONField(help_text='Complete assessment data including categories, criteria, evidence')),
                ('total_score', models.IntegerField(blank=True, help_text='Overall score for quick filtering', null=True)),
                ('passed', models.BooleanField(default=False, help_text='Whether assessment passed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='openai_integration.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['conversation', '-created_at'], name='openai_inte_convers_16f391_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['conversation', 'passed'], name='openai_inte_convers_296efe_idx'),
        ),
    ]
